# Generated by Django 4.2.7 on 2023-11-09 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_pengguna', '0002_lokeraction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lokeraction',
            name='loker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_pengguna.loker'),
        ),
    ]
