# Generated by Django 4.2.7 on 2023-11-29 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_pengguna', '0002_remove_topuphistory_id_topuphistory_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='topuphistory',
            name='directlink_url',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='topuphistory',
            name='img_payment',
            field=models.CharField(default='', max_length=200),
        ),
    ]
