# Generated by Django 4.2.7 on 2023-11-12 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_pengguna', '0002_transaksipeminjaman_uuid_code_delete_lokeraction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifikasi',
            name='waktu',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='topuphistory',
            name='tanggal',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='transaksipeminjaman',
            name='akhirpinjam',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='transaksipeminjaman',
            name='mulaipinjam',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
