# Generated by Django 4.2.7 on 2023-11-28 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_pengguna', '0003_alter_notifikasi_waktu_alter_topuphistory_tanggal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaksipeminjaman',
            name='is_scanned_close',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transaksipeminjaman',
            name='is_scanned_open',
            field=models.BooleanField(default=False),
        ),
    ]
