# Generated by Django 4.2.7 on 2023-11-09 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('app_pengguna', '0003_alter_lokeraction_loker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaksipeminjaman',
            name='loker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_pengguna.loker'),
        ),
        migrations.AlterField(
            model_name='transaksipeminjaman',
            name='pengguna',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.pengguna'),
        ),
    ]
