# Generated by Django 4.2.7 on 2023-11-29 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_pengguna', '0003_topuphistory_directlink_url_topuphistory_img_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='topuphistory',
            name='time',
            field=models.TimeField(auto_now=True),
        ),
    ]
