# Generated by Django 4.2.7 on 2023-11-29 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_admin_is_online'),
        ('app_pengguna', '0004_transaksipeminjaman_is_scanned_close_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifikasi',
            name='pembuat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.admin'),
        ),
    ]
