# Generated by Django 4.2.7 on 2023-11-09 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_pengguna', '0004_alter_transaksipeminjaman_loker_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lokeraction',
            name='img_name',
            field=models.CharField(default='', max_length=36),
        ),
    ]
