# Generated by Django 4.2.7 on 2023-11-30 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_pengguna', '0004_topuphistory_time'),
        ('app_pengguna', '0005_alter_notifikasi_pembuat'),
    ]

    operations = [
    ]
