# Generated by Django 4.2.7 on 2023-11-30 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_pengguna', '0006_merge_20231130_0813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topuphistory',
            name='tanggal',
            field=models.DateField(auto_now=True),
        ),
    ]
