# Generated by Django 4.2.7 on 2023-12-04 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_pengguna', '0006_feedback'),
        ('app_pengguna', '0007_alter_topuphistory_tanggal'),
    ]

    operations = [
    ]
