# Generated by Django 4.2.7 on 2023-12-04 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_admin_is_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='pengguna',
            name='current_free',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='pengguna',
            name='free_peminjaman',
            field=models.IntegerField(default=8),
        ),
    ]
